config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create' 
  delete '/logout', to: 'sessions#destroy'
  

  resources :users do 
    member do 
      get :following, :followers
    end 
  end 
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy] 
  resources :monsters
  resources :items
  

end

app/models/monster.rb
require 'rubygems'
require 'roo'

class Monster < ApplicationRecord
    
  #self.primary_keys = :id, :name
  
  validates :name,  presence: true
  has_many :monster_drops
  has_many :items, through: :monster_drops
  
    
  def drop_item(item_id)
      monster_drops.create(item_id: item_id)
  end 
  
  def get_drop_items
        dropped_items = "SELECT item_id FROM monster_drops
                     WHERE  monster_id = :id"
        Item.where("id IN (#{dropped_items})", id: id)
  end 
  
  
  def remove_drop_item(item)
    monster_drops.find_by(item_id: item.id).destroy 
  end 
  
  def drops?(item)
    monster_drops.include?(item) 
  end   
  
  def image_url
    "https://s3-us-west-1.amazonaws.com/baramlegacy/images/Monsters/#{image_id}.png"
  end
   
  
  
  def self.open_spreadsheet(file)
    case File.extname(file)
    when ".csv" then Roo::Csv.new(file, nil, :ignore)
    when ".xls" then Roo::Excel.new(file, nil, :ignore)
     when ".xlsx" then Roo::Excelx.new(file, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file}"
    end
  end
  
  def self.import(file)
    allowed_attributes = ["sun_id","name","exp","description", "image_id", "color"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    #drop_id = 1
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      monster = new
      monster.id = i - 1
      monster.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k } 
      unless row['item_drops'].nil? 
        row['item_drops'].split(",").map(&:strip).each do |item_name|
          puts item_name
          item_to_drop = Item.find_by(name: item_name) 
          unless item_to_drop.nil? 
              MonsterDrop.create(monster_id: monster.id, item_id: item_to_drop.id )
          end
      end
      monster.save!
      end
    end
  end
  
  
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
    
    before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]

     def show 
        @monster = Monster.find(params[:id])
      # redirect_to root_url and return unless @user.activated?
     end
     
     def index
       @monsters = Monster.all
     end 
     
      
      
      def new
        @monster =  Monster.new
      end
      
      def create
        @monster = Monster.new
         render 'new' 
      end 
      
      def edit 
        @monster = Monster.find(params[:id])
      end 
      
      def update
        @monster = User.find(params[:id])
        if @monster.update_attributes(user_params)
          flash[:success] = "Profile updated" 
          redirect_to @monster
        else 
          render 'edit' 
        end 
      end 
      
      def destroy 
        Monster.find(params[:id]).destroy 
        flash[:success] = "Monster deleted" 
        redirect_to monsters_url
      end 
      
    
      
    
end

app/helpers/monster_helper.rb
module MonsterHelper
end

app/views/monsters/_form.html.erb
<%= form_for(@Monster) url: users_path, html: { multipart: true } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :exp %>
  <%= f.email_field :email, class: 'form-control' %>
  
<% end %>
  

app/views/monsters/_monster.html.erb
 <div class="col-md-2">
    <%= link_to monster_path(monster) do %>
       <div class="squarebox">
          <div class="pid"> 
           <span class="label label-gray"><%= monster.id %> </span>
          </div>
          <div class="pimageid"> 
           <span class="label label-green"><%= monster.image_id %> </span>
          </div>
          <%= image_tag monster.image_url %>
          <p> 
              <%= monster.name %>
          </p>
       </div>
    <% end %>
 </div>

app/views/monsters/index.html.erb
<% provide(:title, 'All Monsters') %>

<h1>Monsters</h1>

<div class="row">
  <%= render @monsters %>
</div>

app/views/monsters/show.html.erb
<% provide(:title,"Monsters: " + @monster.name) %>
<div class="container">
  <div class="page-header">
  <h1><%= @monster.name %></h1>
  </div>
  <div class="row">  
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="overview">
        <h4>Overview</h4>
            <%= render @monster %> 
             
      </div>
    </div>

    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="stats">
           <h4>Stats</h4>
           <table class="table table-striped table-bordered" id="monsterstats">
                <tr>
                  <td> <span class="label label-gray">ID</span></td>
                  <td>  <%= @monster.id %>   </td>
                </tr>
                <tr>
                  <td> <span class="label label-green">EXP</span></td>
                  <td>  <%= @monster.exp %>   </td>
                </tr>
                <tr>
                  <td> <span class="label label-red">HP</span></td>
                  <td>  <%= @monster.hp %>   </td>
                </tr>
                <tr>
                  <td> <span class="label label-blue">MP</span></td>
                  <td>  <%= @monster.mp %>   </td>
                </tr>
                <tr>
                  <td> <span class="label label-orange">Damage</span></td>
                  <td>  <%= @monster.attack_damage %>   </td>
                </tr>
                </table>
        </div>
    </div> 
  </div>
  
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="drops">
          <h4>Item Drops</h4>
            <% @monster.get_drop_items.each do |item| %>
               <%= render item %>
            <% end %>
        </div>
    </div>
  </div>
  
  <div class="row"> 
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="skills">
          <h4>Skills</h4>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="dungeons">
          <h4>Dungeon Locations</h4>
        </div>
    </div>
  </div>
    
  
  
</div> 