config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create' 
  delete '/logout', to: 'sessions#destroy'
  

  resources :users do 
    member do 
      get :following, :followers
    end 
  end 
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy] 
  resources :monsters
  resources :items
  

end

app/models/item.rb
require 'rubygems'
require 'roo'
  
class Item < ApplicationRecord
  #validates :name,  presence: true

  has_many :monster_drops
  has_many :monsters, through: :monster_drops
  
  
  def name_to_id(search_name)
    item.find_by name: search_name
  end
  
  def image_url
    "https://s3-us-west-1.amazonaws.com/baramlegacy/images/Items/#{image_id}.png"
  end
   
  def self.open_spreadsheet(file)
    case File.extname(file)
    when ".csv" then Roo::Csv.new(file, nil, :ignore)
    when ".xls" then Roo::Excel.new(file, nil, :ignore)
     when ".xlsx" then Roo::Excelx.new(file, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file}"
    end
  end
  
  def self.import(file)
    allowed_attributes = ["id","image_id","name"]
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      item = find_by_id(row["id"]) || new
      item.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
      unless item.name == ""
        item.save!
      end
    end
  end
 
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
        
    #before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]

    def show
        @item = Item.find(params[:id])
       # redirect_to root_url and return unless @user.activated?
    end
    
    def index
        @items = Item.all
    end 
    
    def new
      @item =  Item.new
    end
    
    def create
        @monster = Item.new
        render 'new' 
    end 
    
    def edit 
        @item = Item.find(params[:id])
    end 
    
    def update
        @item = User.find(params[:id])
        if @item.update_attributes(user_params)
        flash[:success] = "Profile updated" 
        redirect_to @item
        else 
        render 'edit' 
        end 
    end 
    
    def destroy 
        Item.find(params[:id]).destroy 
        flash[:success] = "Item deleted" 
        redirect_to items_url
    end 
      
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@Item) url: users_path, html: { multipart: true } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :descrption %>
  <%= f.email_field :email, class: 'form-control' %>
  
<% end %>
  

app/views/items/_item.html.erb
 <div class="col-md-2">
    <%= link_to item_path(item) do %>
       <div class="squarebox">
          <div class="pid"> 
           <span class="label label-gray"><%= item.id %> </span>
          </div>
          <div class="pimageid"> 
           <span class="label label-green"><%= item.image_id %> </span>
          </div>
           
          <%= image_tag item.image_url %>
          <p> 
              <%= item.name %>
          </p>
       </div>
    <% end %>
 </div>

app/views/items/index.html.erb
<% provide(:title, 'All Items ') %>

<h1>Items</h1>
<div class="row">
  <%= render @items %>
</div>

app/views/items/show.html.erb
<% provide(:title,"Items: " + @item.name) %>
<div class="container">
  <div class="page-header">
  <h1><%= @item.name %></h1>
  </div>
  <div class="row">  
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
      <div class="overview">
        <h4>Overview</h4>
            <div class="square"> 
             <%= image_tag @item.image_url %>
             <br> 
            </div>
             <p> <%= @item.description %> </p>
             
      </div>
    </div>
    
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="stats">
           <h4>Stats</h4>
           <table class="table table-striped table-bordered" id="monsterstats">
                <tr>
                  <td> <span class="label label-gray">ID</span></td>
                  <td>  <%= @item.id %>   </td>
                </tr>
                <tr>
                  <td> <span class="label label-orange">Description</span></td>
                  <td>  <%= @item.description %>   </td>
                </tr>
                </table>
        </div>
    </div> 
      
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="drops">
          <h4>Monsters that drop this item</h4>
        </div>
        
    </div>
    
    
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="dungeons">
          <h4>Dungeon Locations</h4>
        </div>
    </div>
    
  
  </div>
  
</div> 